theme: jekyll-theme-primer

collections:
  wu:
    output: true
    permalink: /wu/:path/
  blog:
    output: true
    permalink: /blog/:path/

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  auto_ids: true
